### ISSUE TITLE
Demovir doesn't seem to count votes for contigs

### ISSUE THREAD

**Issue by sxh1136** [feargalr/Demovir#10]
Hi there,

I'm under the impression that demovir is supposed to assign taxonomy to each ORF predicted by prodigal and then assign tax to the contig based on the most common classification. From my output it seems that each ORF is just given a classifiction and that the percentage of votes is always 100%. Is this the intended result?

> 
Sequence_ID	Order	Percent_of_votes	Family	Percent_of_votes
NODE_10001_length_1717_cov_4.338147_1 # 11 # 274 # -1 # ID=30947_1;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.386	Caudovirales	100	Siphoviridae	100
NODE_10001_length_1717_cov_4.338147_2 # 289 # 1716 # -1 # ID=30947_2;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.477	Caudovirales	100	Siphoviridae	100
NODE_10007_length_1396_cov_4.014914_2 # 314 # 1396 # -1 # ID=10115_2;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.351	Caudovirales	100	Siphoviridae	100
NODE_1000_length_8519_cov_4.104915_1 # 39 # 2021 # 1 # ID=3790_1;partial=00;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.493	Herpesvirales	100	Herpesviridae	100
NODE_1000_length_8519_cov_4.104915_2 # 2038 # 3909 # 1 # ID=3790_2;partial=00;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.540	Caudovirales	100	Siphoviridae	100
NODE_1000_length_8519_cov_4.104915_4 # 4613 # 5713 # 1 # ID=3790_4;partial=00;start_type=TTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.478	Caudovirales	100	Myoviridae	100
NODE_1000_length_8519_cov_4.104915_8 # 6598 # 6870 # 1 # ID=3790_8;partial=00;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.491	Caudovirales	100	Siphoviridae	100
NODE_1000_length_8519_cov_4.104915_9 # 6877 # 7881 # 1 # ID=3790_9;partial=00;start_type=ATG;rbs_motif=AGGA;rbs_spacer=5-10bp;gc_cont=0.529	Caudovirales	100	Siphoviridae	100

**Comment by qinjunjun** [comment]
> Hi there,
> 
> I'm under the impression that demovir is supposed to assign taxonomy to each ORF predicted by prodigal and then assign tax to the contig based on the most common classification. From my output it seems that each ORF is just given a classifiction and that the percentage of votes is always 100%. Is this the intended result?
> 
> > 
> 
> Sequence_ID Order Percent_of_votes Family Percent_of_votes NODE_10001_length_1717_cov_4.338147_1 # 11 # 274 # -1 # ID=30947_1;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.386 Caudovirales 100 Siphoviridae 100 NODE_10001_length_1717_cov_4.338147_2 # 289 # 1716 # -1 # ID=30947_2;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.477 Caudovirales 100 Siphoviridae 100 NODE_10007_length_1396_cov_4.014914_2 # 314 # 1396 # -1 # ID=10115_2;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.351 Caudovirales 100 Siphoviridae 100 NODE_1000_length_8519_cov_4.104915_1 # 39 # 2021 # 1 # ID=3790_1;partial=00;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.493 Herpesvirales 100 Herpesviridae 100 NODE_1000_length_8519_cov_4.104915_2 # 2038 # 3909 # 1 # ID=3790_2;partial=00;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.540 Caudovirales 100 Siphoviridae 100 NODE_1000_length_8519_cov_4.104915_4 # 4613 # 5713 # 1 # ID=3790_4;partial=00;start_type=TTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.478 Caudovirales 100 Myoviridae 100 NODE_1000_length_8519_cov_4.104915_8 # 6598 # 6870 # 1 # ID=3790_8;partial=00;start_type=ATG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.491 Caudovirales 100 Siphoviridae 100 NODE_1000_length_8519_cov_4.104915_9 # 6877 # 7881 # 1 # ID=3790_9;partial=00;start_type=ATG;rbs_motif=AGGA;rbs_spacer=5-10bp;gc_cont=0.529 Caudovirales 100 Siphoviridae 100

Hello , I used R3.5.1 on a linux server and solved the problem. All programs are in the R3.5.1 microenvironment installed by conda. And then just run it, and he did it. There are five columns.

**Comment by feargalr** [comment]
Thank you for your interest in DemoVir. DemoVir should assign taxonomy to each ORF separately and then generate a consensus approach. If it is not doing that it's likely that it has hit an error or bug. The DemoVir database is out of date and has not been maintained in > 5 years. I would advise you to use an alternative approach for taxonomic classification.
