### ISSUE TITLE
Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF, 

### ISSUE THREAD

**Issue by jojoer2021** [feargalr/Demovir#5]
demovir.sh 8*.fa 4
Genes predicted
UBLAST complete
Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  :
  arguments imply differing number of rows: 0, 123
Execution halted
Done!

help me,please...thanks!!!

**Comment by SergeyBaikal** [comment]
sh demovir.sh input.fasta threads 8

In my opinion there should be one file with contigs.

**Comment by SergeyBaikal** [comment]
The database already needs to be updated. It contains only 3 Caudovirales families, now there are 14 of them.

**Comment by wangyaxiang008** [comment]
> demovir.sh 8*.fa 4
> Genes predicted
> UBLAST complete
> Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF, :
> arguments imply differing number of rows: 0, 123
> Execution halted
> Done!
> 
> help me,please...thanks!!!

hi @jojoer2021 @SergeyBaikal 
  I encountered the same problem as you, how can you solve it later?
  This is my wrong report:_
          job-41466_2.err
          Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  : 
                arguments imply differing number of rows: 0, 4453
         Execution halted_

Wish for your reply,thank you!

**Comment by ErnieHsieh** [comment]
Hello,

I also met the similar problem to you, does anyone know how to resolve it please?

> Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  : 
  arguments imply differing number of rows: 0, 28712
Execution halted

Many thanks in advance if anyone knows it!

Ernie

**Comment by wangyaxiang008** [comment]
> Hello,
> 
> I also met the similar problem to you, does anyone know how to resolve it please?
> 
> > Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  :
> > arguments imply differing number of rows: 0, 28712
> > Execution halted
> 
> Many thanks in advance if anyone knows it!
> 
> Ernie

You can configure a virtual environment of R-3.5 with miniconda3, and then re-installed other  software.
Hope to be useful to you

wyx

**Comment by ErnieHsieh** [comment]
> > Hello,
> > I also met the similar problem to you, does anyone know how to resolve it please?
> > > Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  :
> > > arguments imply differing number of rows: 0, 28712
> > > Execution halted
> > 
> > 
> > Many thanks in advance if anyone knows it!
> > Ernie
> 
> You can configure a virtual environment of R-3.5 with miniconda3, and then re-installed other software.
> Hope to be useful to you
> 
> wyx

Hi,

Thanks for your suggestion. I have solved this problem and can generate the output. However, I meet a new issue: the output is empty and only shows the headers of five columns. Did I miss anything else so that the output is still incorrect?

Thanks.
Ernie

**Comment by TomasaSbaffi** [comment]
Indeed, I previously set up a conda env with the newest R-base for my server but for some reason it did not support the table building and it showed the `arguments imply differing number of rows ` error. However I then built a new conda environment specifying 
`conda install -c conda-forge r-base=3.5.1`
and it works fine.

I am not sure whether the empty output means that no matches were found or there was any mistake, it is strange that none of the contigs in your fasta give no output at all.

**Comment by BenMinch** [comment]
There is an error in their R script. I was getting the same problem and had to change to levels(factor(results3$contig)

**Comment by feargalr** [comment]
Thanks all for your interest in DemoVir. I developed this at a request of a prior research group I working with >5 years ago. No one has actively maintained this classification system in years and as some of you have pointed out this database is out of date. Thus I would advise users not to use this and I will be archiving this repository and redirecting users elsewhere.
