### ISSUE TITLE
Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  :

### ISSUE THREAD

**Issue by yuanpingdu** [feargalr/Demovir#6]
When I run the command "Rscript  demovir.R",the error shows:
Error in data.frame(levels(results3$contig), taxassO, margin_o, taxassF,  :
  arguments imply differing number of rows: 0, 100
Execution halted

I have print out the "margin_f",there is blank information, 
    Mimiviridae    Siphoviridae      Myoviridae      Myoviridae    Siphoviridae
            100             100             100             100             100
                   Siphoviridae      Myoviridae      Poxviridae    Siphoviridae
             NA             100             100             100             100
how should I do to make it normally?

**Comment by yuanpingdu** [comment]
![image](https://user-images.githubusercontent.com/25142771/129659342-1b709ad5-2db7-4e10-aef0-651fa7b7f407.png)

**Comment by feargalr** [comment]
Without input and output files I am unable to recreate this error. However, the DemoVir database is out of date and has not been updated in > 5 years. I would advise you to use an alternative approach for taxonomic classification.
