### ISSUE TITLE
Error in running Demovir

### ISSUE THREAD

**Issue by ErnieHsieh** [feargalr/Demovir#7]
Hi, 

While running this tool in macOS 11.5.2, I got the following error but couldn't understand it as I am new to bioinformatics with a little knowledge about coding/programming. Can someone help me with this issue please?

I am working on a viral metagenomic data and so would like to use it for getting taxonomic annotation on my viral contigs.

The error which I got is as follows:

Genes predicted
UBLAST complete
sort: No such file or directory
rm: trembl_ublast.viral.txt: No such file or directory
Error in read.table(file = file, header = header, sep = sep, quote = quote, :
no lines available in input
Calls: read.delim -> read.table
Execution halted
Done! 

I installed required components, downloaded nr.95.fasta.bz2 database from FigShare and put it in the Demovir directory, followed by using chmod 777 to get all permissions for all files in Demovir directory including format_db.sh, and then ran the programme in a folder at the desktop: /path_to_demovir/demovir.sh input.fasta threads.

If there's anything wrong or I misunderstood it please help me correct it. Many thanks!

Ernie

**Comment by chengzhongyi8** [comment]
Same error. Are you solved it?

**Comment by chengzhongyi8** [comment]
Same error. Do you solve it?
