### ISSUE TITLE
empty output after installing, how can I solve this?

### ISSUE THREAD

**Issue by drelo** [feargalr/Demovir#8]
Dear all, I would like to use this software since a colleague recommended it to me and I have seen it applied in several publications.  I have thousands of configs already filtered with virfinder and  I have the following installed in a Fedora installation:

```
R version 3.6.3
Prodigal V2.6.3: February, 2016
usearch v11.0.667_i86linux32 (I put the binary in the bin folder I called it usearch)
bz2 is already installed
```

I followed the installation and after downloading the nr.95.fasta.bz2 I used some data as an example. I then used format_db.sh first.

After several tries I am trying it [against this sequence](https://www.ncbi.nlm.nih.gov/nucleotide/BK027341.1?report=genbank&log$=nuclalign&blast_rank=1&RID=ZK4GE8Z9013) of a known virus to see if I can get a match.   
Could you help me diagnose this error or how to solve this issue? Thanks in advance!

Andrés

**Comment by SiNoWu** [comment]
Alter the demovir.R.
```
taxassO[sums_o>1] = "Unassigned"
taxassF[sums_f>1] = "Unassigned"

towrite = data.frame(levels(factor(results3$contig)),taxassO,margin_o,taxassF,margin_f)
```
I'm not sure about that, but it works ok.

**Comment by drelo** [comment]
That fix worked, thanks  a lot! 
The output is below and it got 5/7 for the correct family.

```
Sequence_ID	Order	Percent_of_votes	Family	Percent_of_votes
MH510275.1_23 # 15639 # 16277 # 1 # ID=1_23;partial=00;start_type=ATG;rbs_motif=AGGAG/GGAGG;rbs_spacer=11-12bp;gc_cont=0.441	Caudovirales	100	Myoviridae	100
MH510275.1_24 # 16288 # 17022 # 1 # ID=1_24;partial=00;start_type=GTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.424	Caudovirales	100	Siphoviridae	100
MH510275.1_25 # 17022 # 17372 # 1 # ID=1_25;partial=00;start_type=ATG;rbs_motif=GGAG/GAGG;rbs_spacer=5-10bp;gc_cont=0.456	Caudovirales	100	Myoviridae	100
MH510275.1_26 # 17373 # 17777 # 1 # ID=1_26;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.464	Caudovirales	100	Siphoviridae	100
MH510275.1_27 # 17796 # 19466 # 1 # ID=1_27;partial=00;start_type=GTG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.478	Caudovirales	100	Myoviridae	100
MH510275.1_31 # 20784 # 21158 # 1 # ID=1_31;partial=00;start_type=GTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.427	Caudovirales	100	Myoviridae	100
MH510275.1_37 # 25886 # 26347 # 1 # ID=1_37;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.461	Caudovirales	100	Myoviridae	100
```

**Comment by qinjunjun** [comment]
> That fix worked, thanks a lot! The output is below and it got 5/7 for the correct family.
> 
> ```
> Sequence_ID	Order	Percent_of_votes	Family	Percent_of_votes
> MH510275.1_23 # 15639 # 16277 # 1 # ID=1_23;partial=00;start_type=ATG;rbs_motif=AGGAG/GGAGG;rbs_spacer=11-12bp;gc_cont=0.441	Caudovirales	100	Myoviridae	100
> MH510275.1_24 # 16288 # 17022 # 1 # ID=1_24;partial=00;start_type=GTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.424	Caudovirales	100	Siphoviridae	100
> MH510275.1_25 # 17022 # 17372 # 1 # ID=1_25;partial=00;start_type=ATG;rbs_motif=GGAG/GAGG;rbs_spacer=5-10bp;gc_cont=0.456	Caudovirales	100	Myoviridae	100
> MH510275.1_26 # 17373 # 17777 # 1 # ID=1_26;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.464	Caudovirales	100	Siphoviridae	100
> MH510275.1_27 # 17796 # 19466 # 1 # ID=1_27;partial=00;start_type=GTG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.478	Caudovirales	100	Myoviridae	100
> MH510275.1_31 # 20784 # 21158 # 1 # ID=1_31;partial=00;start_type=GTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.427	Caudovirales	100	Myoviridae	100
> MH510275.1_37 # 25886 # 26347 # 1 # ID=1_37;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.461	Caudovirales	100	Myoviridae	100
> ```

Hello,I would like to ask you a qusetion, in rusult ,thi first column is contig odr ORF id? Thank you a lot

**Comment by qinjunjun** [comment]
> That fix worked, thanks a lot! The output is below and it got 5/7 for the correct family.
> 
> ```
> Sequence_ID	Order	Percent_of_votes	Family	Percent_of_votes
> MH510275.1_23 # 15639 # 16277 # 1 # ID=1_23;partial=00;start_type=ATG;rbs_motif=AGGAG/GGAGG;rbs_spacer=11-12bp;gc_cont=0.441	Caudovirales	100	Myoviridae	100
> MH510275.1_24 # 16288 # 17022 # 1 # ID=1_24;partial=00;start_type=GTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.424	Caudovirales	100	Siphoviridae	100
> MH510275.1_25 # 17022 # 17372 # 1 # ID=1_25;partial=00;start_type=ATG;rbs_motif=GGAG/GAGG;rbs_spacer=5-10bp;gc_cont=0.456	Caudovirales	100	Myoviridae	100
> MH510275.1_26 # 17373 # 17777 # 1 # ID=1_26;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.464	Caudovirales	100	Siphoviridae	100
> MH510275.1_27 # 17796 # 19466 # 1 # ID=1_27;partial=00;start_type=GTG;rbs_motif=GGAGG;rbs_spacer=5-10bp;gc_cont=0.478	Caudovirales	100	Myoviridae	100
> MH510275.1_31 # 20784 # 21158 # 1 # ID=1_31;partial=00;start_type=GTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.427	Caudovirales	100	Myoviridae	100
> MH510275.1_37 # 25886 # 26347 # 1 # ID=1_37;partial=00;start_type=ATG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.461	Caudovirales	100	Myoviridae	100
> ```

Hello,I would like to ask you a qusetion, in rusult ,thi first column is contig or ORF id? Thank you a lot
